# Generated by Django 5.2 on 2025-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
