# Generated by Django 5.2 on 2025-04-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_project_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Done',
            new_name='done',
        ),
    ]
