# Generated by Django 5.2 on 2025-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_done_project_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='done',
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
